backend:
  name: git-gateway
  branch: gh-pages # Branch to update (optional; defaults to master)
collections:
  - 
    label: Meetup
    name: meetup
    folder: .
    fields: 
      - 
        label: Layout
        name: layout
        widget: select
        options: ["record", "toplevel"]
      - 
        label: Title
        name: title
        widget: string
media_folder: images/uploads/
